# Generated by Django 3.1.6 on 2021-02-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id_scheduling', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('canceled', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=100, null=True)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointments', to='patient.patients')),
            ],
            options={
                'db_table': 'Appointments',
                'managed': True,
                'unique_together': {('date_time', 'id_patient')},
            },
        ),
    ]
