# Generated by Django 3.1.7 on 2021-03-16 00:17

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesHistorical',
            fields=[
                ('id_image_historical', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=images.models.images_historical)),
                ('id_historical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='records.records')),
            ],
        ),
    ]
