# Generated by Django 3.1.6 on 2021-02-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=80)),
                ('number_address', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=100)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('rg', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patients',
                'managed': True,
            },
        ),
    ]
